### ISSUE TITLE
Corinne's Carbuncles and Bomb Model

### ISSUE THREAD

**Issue by zunath** [zunath/NWN.FinalFantasy.Content#10]
https://cdn.discordapp.com/attachments/640163587087794204/729962300840083506/3_carbuncles__bomb.rar

Add these to our hakset

**Comment by zunath** [comment]
This might be included in the previous set. If it is, don't add it again.

https://cdn.discordapp.com/attachments/640163587087794204/729806447747006534/c_carbuncle.rar

**Comment by Cavcode** [comment]
Just added these in the latest PR.
